-- Supabase schema for Stock Plot Center
-- Basado en la estructura original de u956355532_sto (MySQL)

begin;

-- Extensiones necesarias
create extension if not exists "uuid-ossp";
create extension if not exists "pgcrypto";

-- Función reutilizable para updated_at
create or replace function public.set_updated_at()
returns trigger as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$ language plpgsql;

-- Tabla de usuarios (metadatos ligados a auth.users)
create table if not exists public.users (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null unique,
  name text not null default 'Usuario',
  role text not null default 'Mostrador',
  avatar_url text,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create trigger set_timestamp_users
before update on public.users
for each row execute function public.set_updated_at();

-- Tabla articulos (materiales)
create table if not exists public.articulos (
  id integer generated by default as identity primary key,
  codigo varchar(50) not null unique,
  descripcion varchar(255) not null,
  sector varchar(50) not null default 'Gral',
  imagen text,
  stock integer not null default 100,
  stock_minimo integer not null default 10,
  precio numeric(10,2) not null default 0,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create trigger set_timestamp_articulos
before update on public.articulos
for each row execute function public.set_updated_at();

create index if not exists articulos_sector_idx on public.articulos (sector);
create index if not exists articulos_codigo_idx on public.articulos (codigo);

-- Tabla pedidos
create table if not exists public.pedidos (
  id integer generated by default as identity primary key,
  client_name varchar(255) not null,
  description text not null,
  image_url text,
  status varchar(50) not null default 'Pendiente',
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  user_id uuid references public.users(id) on delete set null,
  approval_status varchar(50) not null default 'Pendiente',
  approved_by uuid references public.users(id) on delete set null,
  approved_at timestamptz,
  rejection_reason text
);

create trigger set_timestamp_pedidos
before update on public.pedidos
for each row execute function public.set_updated_at();

create index if not exists pedidos_user_idx on public.pedidos (user_id);
create index if not exists pedidos_status_idx on public.pedidos (status);
create index if not exists pedidos_approval_status_idx on public.pedidos (approval_status);

-- Tabla pedidos_items
create table if not exists public.pedidos_items (
  id integer generated by default as identity primary key,
  pedido_id integer not null references public.pedidos(id) on delete cascade,
  articulo_id integer not null references public.articulos(id) on delete cascade,
  cantidad integer not null,
  stock_disponible integer default 0,
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists pedidos_items_pedido_idx on public.pedidos_items (pedido_id);
create index if not exists pedidos_items_articulo_idx on public.pedidos_items (articulo_id);

-- Tabla ordenes_compra
create table if not exists public.ordenes_compra (
  id integer generated by default as identity primary key,
  articulo_id integer not null references public.articulos(id) on delete restrict,
  cantidad integer not null,
  proveedor varchar(255) default 'Por definir',
  observaciones text,
  solicitado_por uuid references public.users(id) on delete set null,
  pedido_id integer references public.pedidos(id) on delete set null,
  status varchar(50) not null default 'Pendiente',
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create trigger set_timestamp_ordenes_compra
before update on public.ordenes_compra
for each row execute function public.set_updated_at();

create index if not exists ordenes_compra_status_idx on public.ordenes_compra (status);
create index if not exists ordenes_compra_articulo_idx on public.ordenes_compra (articulo_id);

-- Tabla movimientos_caja
create table if not exists public.movimientos_caja (
  id integer generated by default as identity primary key,
  tipo varchar(50) not null check (tipo in ('Ingreso','Egreso')),
  categoria varchar(100) not null default 'General',
  concepto varchar(255) not null,
  monto numeric(10,2) not null,
  metodo_pago varchar(50) not null default 'Efectivo',
  user_id uuid references public.users(id) on delete set null,
  pedido_id integer references public.pedidos(id) on delete set null,
  observaciones text,
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists movimientos_caja_tipo_idx on public.movimientos_caja (tipo);
create index if not exists movimientos_caja_user_idx on public.movimientos_caja (user_id);

-- Tabla notifications
create table if not exists public.notifications (
  id integer generated by default as identity primary key,
  user_id uuid not null references public.users(id) on delete cascade,
  title varchar(255),
  message text not null,
  type varchar(50) not null default 'order_update',
  related_id integer,
  is_read boolean not null default false,
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists notifications_user_idx on public.notifications (user_id);
create index if not exists notifications_is_read_idx on public.notifications (is_read);

-- Tabla comments
create table if not exists public.comments (
  id integer generated by default as identity primary key,
  pedido_id integer not null references public.pedidos(id) on delete cascade,
  user_id uuid not null references public.users(id) on delete cascade,
  content text not null,
  created_at timestamptz not null default timezone('utc', now())
);

-- Tabla messages (mensajería interna futura)
create table if not exists public.messages (
  id integer generated by default as identity primary key,
  sender_id uuid not null references public.users(id) on delete cascade,
  recipient_id uuid references public.users(id) on delete cascade,
  subject varchar(255),
  channel varchar(100),
  content text not null,
  created_at timestamptz not null default timezone('utc', now())
);

-- Tabla configuracion (parámetros globales)
create table if not exists public.configuracion (
  id integer generated by default as identity primary key,
  clave varchar(100) not null unique,
  valor text not null,
  descripcion varchar(255),
  updated_at timestamptz not null default timezone('utc', now())
);

create trigger set_timestamp_configuracion
before update on public.configuracion
for each row execute function public.set_updated_at();

-- Habilitar RLS
alter table public.users enable row level security;
alter table public.articulos enable row level security;
alter table public.pedidos enable row level security;
alter table public.pedidos_items enable row level security;
alter table public.ordenes_compra enable row level security;
alter table public.movimientos_caja enable row level security;
alter table public.notifications enable row level security;
alter table public.comments enable row level security;
alter table public.messages enable row level security;
alter table public.configuracion enable row level security;

-- Políticas básicas (permitir solo a usuarios autenticados)
create policy "Users can read profiles" on public.users
for select using (auth.role() = 'authenticated');

create policy "Service role manages users" on public.users
for all using (auth.role() = 'service_role') with check (auth.role() = 'service_role');

create policy "Authenticated can read articulos" on public.articulos
for select using (auth.role() = 'authenticated');

create policy "Authenticated can manage articulos" on public.articulos
for all using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');

create policy "Authenticated can read pedidos" on public.pedidos
for select using (auth.role() = 'authenticated');

create policy "Authenticated can manage pedidos" on public.pedidos
for all using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');

create policy "Authenticated can read pedidos_items" on public.pedidos_items
for select using (auth.role() = 'authenticated');

create policy "Authenticated can manage pedidos_items" on public.pedidos_items
for all using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');

create policy "Authenticated can read ordenes_compra" on public.ordenes_compra
for select using (auth.role() = 'authenticated');

create policy "Authenticated can manage ordenes_compra" on public.ordenes_compra
for all using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');

create policy "Authenticated can read movimientos_caja" on public.movimientos_caja
for select using (auth.role() = 'authenticated');

create policy "Authenticated can manage movimientos_caja" on public.movimientos_caja
for all using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');

create policy "Authenticated can read notifications" on public.notifications
for select using (auth.uid() = user_id);

create policy "Authenticated can manage notifications" on public.notifications
for all using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');

create policy "Authenticated can read comments" on public.comments
for select using (auth.role() = 'authenticated');

create policy "Authenticated can manage comments" on public.comments
for all using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');

create policy "Authenticated can read messages" on public.messages
for select using (auth.role() = 'authenticated');

create policy "Authenticated can manage messages" on public.messages
for all using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');

create policy "Authenticated can read configuracion" on public.configuracion
for select using (auth.role() = 'authenticated');

create policy "Authenticated can manage configuracion" on public.configuracion
for all using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');

commit;

